name: surveyexport

on: push

jobs:
  my_checks:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: install dependencies
        run: |
          make install
      - name: run tests
        run: |
          make test
      - name: run lint
        run: |
          make lint

      #AWS
      - name: AWS integration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PERSONAL }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PERSONAL }}
          aws-region: ${{ secrets.AWS_REGION_PERSONAL }}
      # sam build
      - name: build 
        run: sam build

      - name: deploy on personal account
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name wordexport --region ${{ secrets.AWS_REGION_PERSONAL }} #--s3-bucket s3-bucket-name